# .github/workflows/terraform-plan.yml
name: Terraform AWS Plan # Nome do workflow atualizado para refletir o foco no plano

on:
  push: # Aciona o workflow em qualquer push para o repositório
    branches:
      - main # Opcional: você pode especificar branches aqui, como 'main' ou 'develop'
  workflow_dispatch: # Permite acionar o workflow manualmente

jobs:
  terraform_plan: # Nome do job atualizado
    name: 'Terraform Plan' # Nome de exibição do job
    runs-on: ubuntu-latest # Executa em um runner Ubuntu
    defaults:
      run:
        shell: bash # Define o shell padrão para as etapas

    # Define as variáveis de ambiente para as credenciais da AWS
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_pub_key: ${{ secrets.aws_pub_key }} # Variável de ambiente para a chave pública AWS

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Faz o checkout do seu repositório (atualizado para v4)

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3 # Configura o Terraform CLI
        with:
          terraform_version: 1.x.x # Use a versão do Terraform que você preferir (ex: 1.5.7)

      - name: Terraform Init
        run: terraform init # Inicializa o diretório de trabalho do Terraform

      - name: Terraform Validate
        run: terraform validate # Valida a sintaxe dos arquivos Terraform

      - name: Terraform Plan # Etapa para gerar o plano de execução do Terraform
        run: terraform plan # Gera o plano
