name: Terraform AWS Plan

on:
  push:
    branches:
      - main # Dispara o workflow quando há um push na branch 'main'

jobs:
  terraform_plan:
    name: 'Terraform Plan/Apply'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_pub_key: ${{ secrets.aws_pub_key }}
      TF_LOG: TRACE
      TF_LOG_PATH: tf_trace.log

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
        # Se você tiver um 'terraform apply -auto-approve' aqui, a criação do bucket
        # ocorrerá antes do upload.

      # --- ETAPAS PARA UPLOAD DO PDF ---

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Certifique-se de que esta é a região correta do seu bucket S3

      - name: Get S3 Bucket Name from Terraform Output
        id: get_bucket_name
        run: echo "S3_BUCKET_NAME=$(terraform output -raw open_webui_s3_bucket_name)" >> "$GITHUB_OUTPUT"
        working-directory: .

      # --- AQUI ESTÁ A MUDANÇA: APONTANDO PARA O ARQUIVO ESPECÍFICO ---
      - name: Upload AWS CLI PDF to S3
        run: |
          PDF_FILE_PATH="./docs/AWS Command Line Interface.pdf" # Caminho do arquivo específico
          BUCKET_NAME="${{ steps.get_bucket_name.outputs.S3_BUCKET_NAME }}"
          S3_DEST_KEY="docs/AWS_Command_Line_Interface.pdf" # Caminho e nome do arquivo no S3.
                                                          # Ajustei o nome para evitar espaços e caracteres especiais
                                                          # no objeto S3, o que é uma boa prática.
                                                          # Você pode manter o nome original se preferir,
                                                          # mas pode causar problemas em algumas ferramentas.

          echo "Iniciando upload de $PDF_FILE_PATH para s3://$BUCKET_NAME/$S3_DEST_KEY"

          if [ -f "$PDF_FILE_PATH" ]; then # Verifica se o arquivo existe (usando -f para arquivo)
            aws s3 cp "$PDF_FILE_PATH" "s3://$BUCKET_NAME/$S3_DEST_KEY" --acl public-read # Opcional: --acl public-read para acesso público
            echo "PDF 'AWS Command Line Interface.pdf' enviado com sucesso para s3://$BUCKET_NAME/$S3_DEST_KEY"
          else
            echo "Arquivo PDF '$PDF_FILE_PATH' não encontrado. Pulando o upload."
            exit 1 # Opcional: Falhar o job se o arquivo não existir
          fi