name: Terraform AWS Plan 
on: push

jobs:
  terraform_plan: # Nome do job atualizado
    name: 'Terraform Plan' # Nome de exibição do job
    runs-on: ubuntu-latest # Executa em um runner Ubuntu
    defaults:
      run:
        shell: bash # Define o shell padrão para as etapas

    # Define as variáveis de ambiente para as credenciais da AWS
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_pub_key: ${{ secrets.aws_pub_key }}
      TF_LOG: TRACE
      TF_LOG_PATH: tf_trace.log     

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3 

      - name: Terraform Init
        run: terraform init 

      - name: Terraform Validate
        run: terraform validate 

      - name: Terraform Plan 
        run: terraform plan 